### ISSUE TITLE
URLが長すぎるので、せめてPATH部分だけでも短くしたい

### ISSUE THREAD

**Issue by kakudo415** [RICORA/RICORA_HP#13]
現状、トップページさえ「www.ed.tus.ac.jp/ricora/lang/RICORA_HP/docs/index.html」なる長大なURLになっていて見栄えが悪いように思います。
ドメインは大学管理なので仕方ないですが、PATH部分は例えば「www.ed.tus.ac.jp/ricora/programming/」とかでアクセスできるようになってほしい。
具体的な方法としてはシンボリックリンクを貼る等がありますが、その場合はHTML等からの参照URLも適宜書き換える必要があり、そうするとローカルで開発するときにめんどくささがありそうです。

**Comment by Shinonome517** [comment]
選択肢として、無料の短縮リンクサービスを使うという選択肢もあります

**Comment by kakudo415** [comment]
URL短縮サービスは、URLがもつ意味（ドメインとかパス）とかを失わせてしまうので、今回のような決まったホームページに使うという用途では不適だと思います。

**Comment by Shinonome517** [comment]
解決したので閉じます！！
